#serverless.yml

service: bucket-antivirus-function
package:
  artifact: clambda.zip

provider:
  name: aws
  region: us-east-2
  stage: ${opt:stage, 'dev'}
  runtime: python2.7
  timeout: 300
  environment:
      AV_DEFINITION_S3_BUCKET: ${env:AV_DEFINITION_S3_BUCKET}
      DATADOG_API_KEY: ${env:DATADOG_API_KEY}

functions:
  clambda-antivirus-update-ez-test:
    handler: update.lambda_handler
    name: clambda-antivirus-update
    description: Updates the antivirus definitions and adds them to the bucket.
    memorySize: 512
    role: arn:aws:iam::#{AWS::AccountId}:role/service-role/clambda-antivirus-update
    events:
      - schedule: rate(3 hours)


  clambda-antivirus-function-ez-test:
    handler: scan.lambda_handler
    name: clambda-antivirus-scan
    description: Performs the scan and tags the file CLEAN / INFECTED.
    memorySize: 1024
    role: arn:aws:iam::#{AWS::AccountId}:role/service-role/clambda-antivirus-scan

plugins:
  - serverless-pseudo-parameters
